export const SAVE_KEY = 'bureaucracy-tycoon-save-v1';

export const ECONOMY = {
    startingMoney: 0,
    startingPendingForms: 3,
    startingCapacity: 14,
    startingMoneyPerForm: 1,
    startingMoneyMultiplier: 1,
    startingArrivalRate: 1.2,
    startingAutoProcessRate: 0,
    manualProcessAmount: 2,
    approvalLayerBonus: 0.22,
    overflowWarningThreshold: 0.9,
    surgeQueueThreshold: 0.75,
    surgeIntervalSeconds: 6,
    surgeProcessAmount: 3,
    passiveSaveSeconds: 5,
    tickRateMs: 100,
    logLimit: 4,
    contractBudgetRewardMultiplier: 1.6,
};

export const UPGRADE_DEFINITIONS = {
    betterInk: {
        id: 'betterInk',
        title: 'Premium Plan',
        tier: 'office',
        description: '+$1 revenue per shipped feature',
        baseCost: 8,
        costScale: 1.42,
    },
    largerInbox: {
        id: 'largerInbox',
        title: 'Better Task Board',
        tier: 'office',
        description: '+8 backlog capacity',
        baseCost: 20,
        costScale: 1.52,
    },
    juniorClerk: {
        id: 'juniorClerk',
        title: 'First Engineer',
        tier: 'office',
        description: '+1 team output per second',
        baseCost: 12,
        costScale: 1.5,
    },
    marketingCampaign: {
        id: 'marketingCampaign',
        title: 'Launch Push',
        tier: 'office',
        description: '+0.75 new tasks per second',
        baseCost: 16,
        costScale: 1.5,
    },
    complianceDesk: {
        id: 'complianceDesk',
        title: 'Monetization Stack',
        tier: 'department',
        description: '+25% revenue multiplier',
        baseCost: 52,
        costScale: 1.72,
    },
    approvalLayer: {
        id: 'approvalLayer',
        title: 'New Department',
        tier: 'department',
        description: 'Increase office level and boost all scaling',
        baseCost: 90,
        costScale: 1.95,
    },
    expressWindow: {
        id: 'expressWindow',
        title: 'Founder Focus',
        tier: 'office',
        description: '+1 feature per manual ship',
        baseCost: 20,
        costScale: 1.62,
    },
    seniorClerk: {
        id: 'seniorClerk',
        title: 'Senior Engineer',
        tier: 'department',
        description: '+2 team output per second',
        baseCost: 70,
        costScale: 1.82,
        unlockFlag: 'unlock-senior-clerk',
        unlockMessage: 'Senior Engineer unlocked. Your first serious hire changes the pace.',
    },
    efficiencyOffice: {
        id: 'efficiencyOffice',
        title: 'Internal Tooling',
        tier: 'agency',
        description: '+15% shipping efficiency',
        baseCost: 85,
        costScale: 1.88,
    },
    doubleStamp: {
        id: 'doubleStamp',
        title: 'Sprint Planning',
        tier: 'department',
        description: '+1 extra feature per manual ship',
        baseCost: 90,
        costScale: 2.2,
        maxLevel: 1,
        unlockFlag: 'unlock-double-stamp',
        unlockMessage: 'Sprint Planning unlocked. Founder work now moves in tighter batches.',
    },
    surgeProtocol: {
        id: 'surgeProtocol',
        title: 'Release Train',
        tier: 'agency',
        description: 'Every 6 seconds, burst-ship 3 features when the backlog is crowded',
        baseCost: 160,
        costScale: 2.35,
        maxLevel: 1,
        unlockFlag: 'unlock-surge-protocol',
        unlockMessage: 'Release Train unlocked. Crowded sprints now trigger burst shipping.',
    },
    bulkFiling: {
        id: 'bulkFiling',
        title: 'Product Process',
        tier: 'department',
        description: '+3 features per manual ship',
        baseCost: 110,
        costScale: 2.2,
        maxLevel: 1,
        unlockFlag: 'unlock-bulk-filing',
        unlockMessage: 'Product Process unlocked. Big batches can now ship at once.',
    },
    overtimeProgram: {
        id: 'overtimeProgram',
        title: 'CI/CD Pipeline',
        tier: 'department',
        description: 'Breakthrough: double team output',
        baseCost: 160,
        costScale: 2.35,
        maxLevel: 1,
        unlockFlag: 'unlock-overtime-program',
        unlockMessage: 'CI/CD Pipeline unlocked. Team output just doubled.',
    },
    federalSubsidy: {
        id: 'federalSubsidy',
        title: 'Series A',
        tier: 'agency',
        description: 'Double all revenue',
        baseCost: 280,
        costScale: 2.5,
        maxLevel: 1,
        unlockFlag: 'unlock-federal-subsidy',
        unlockMessage: 'Series A unlocked. Growth capital just hit the runway.',
    },
};

export const STATUS_MESSAGES = {
    arrival: [
        'A fresh customer request landed in the backlog.',
        'Another product idea just came in from users.',
        'Bug reports and feature requests are piling up.',
        'The roadmap just got one line longer.',
    ],
    automation: [
        'An engineer closed a task before standup ended.',
        'A clean handoff pushed work through the sprint board.',
        'Internal tooling shaved a little time off the release.',
        'The team shipped without waiting on the founder.',
    ],
    growth: [
        'A new department formed and the org chart grew.',
        'Operations tightened up the release process.',
        'The team finally booked a room with a whiteboard.',
        'A new manager showed up with a cleaner roadmap.',
    ],
    unlocked: [
        'The startup just hit a new level of momentum.',
        'Investors are finally returning your emails.',
        'The next stage of growth is starting to feel real.',
    ],
};
