export const SAVE_KEY = 'bureaucracy-tycoon-save-v1';

export const ECONOMY = {
    startingMoney: 0,
    startingPendingForms: 3,
    startingCapacity: 14,
    startingMoneyPerForm: 1,
    startingMoneyMultiplier: 1,
    startingArrivalRate: 1.2,
    startingAutoProcessRate: 0,
    manualProcessAmount: 2,
    approvalLayerBonus: 0.22,
    overflowWarningThreshold: 0.9,
    surgeQueueThreshold: 0.75,
    surgeIntervalSeconds: 6,
    surgeProcessAmount: 3,
    passiveSaveSeconds: 5,
    tickRateMs: 100,
    logLimit: 4,
    contractBudgetRewardMultiplier: 1.6,
};

export const UPGRADE_DEFINITIONS = {
    betterInk: {
        id: 'betterInk',
        title: 'Premium Clients',
        tier: 'office',
        description: '+$1 cash per completed order',
        baseCost: 8,
        costScale: 1.42,
    },
    largerInbox: {
        id: 'largerInbox',
        title: 'Expanded Storage',
        tier: 'office',
        description: '+8 storage capacity',
        baseCost: 20,
        costScale: 1.52,
    },
    juniorClerk: {
        id: 'juniorClerk',
        title: 'Street Runner',
        tier: 'office',
        description: '+1 operations per second',
        baseCost: 12,
        costScale: 1.5,
    },
    marketingCampaign: {
        id: 'marketingCampaign',
        title: 'Supplier Network',
        tier: 'office',
        description: '+0.75 incoming orders per second',
        baseCost: 16,
        costScale: 1.5,
    },
    complianceDesk: {
        id: 'complianceDesk',
        title: 'High-Value Deals',
        tier: 'department',
        description: '+25% cash multiplier',
        baseCost: 52,
        costScale: 1.72,
    },
    approvalLayer: {
        id: 'approvalLayer',
        title: 'Chain of Command',
        tier: 'department',
        description: 'Increase network tier and boost all scaling',
        baseCost: 90,
        costScale: 1.95,
    },
    expressWindow: {
        id: 'expressWindow',
        title: 'Quick Drop',
        tier: 'office',
        description: '+1 order per manual fulfill',
        baseCost: 20,
        costScale: 1.62,
    },
    seniorClerk: {
        id: 'seniorClerk',
        title: 'Trusted Operator',
        tier: 'department',
        description: '+2 operations per second',
        baseCost: 70,
        costScale: 1.82,
        unlockFlag: 'unlock-senior-clerk',
        unlockMessage: 'Trusted Operator unlocked. The crew just got sharper and faster.',
    },
    efficiencyOffice: {
        id: 'efficiencyOffice',
        title: 'Smuggling Routes',
        tier: 'agency',
        description: '+15% operation efficiency',
        baseCost: 85,
        costScale: 1.88,
    },
    doubleStamp: {
        id: 'doubleStamp',
        title: 'Dual Shipment',
        tier: 'department',
        description: '+1 extra order per manual fulfill',
        baseCost: 90,
        costScale: 2.2,
        maxLevel: 1,
        unlockFlag: 'unlock-double-stamp',
        unlockMessage: 'Dual Shipment unlocked. One move can now clear two orders at once.',
    },
    surgeProtocol: {
        id: 'surgeProtocol',
        title: 'Sweep Crew',
        tier: 'agency',
        description: 'Every 6 seconds, burst-fulfill 3 orders when storage is crowded',
        baseCost: 160,
        costScale: 2.35,
        maxLevel: 1,
        unlockFlag: 'unlock-surge-protocol',
        unlockMessage: 'Sweep Crew unlocked. Packed storage now triggers a fast cleanup run.',
    },
    bulkFiling: {
        id: 'bulkFiling',
        title: 'Bulk Drop',
        tier: 'department',
        description: '+3 orders per manual fulfill',
        baseCost: 110,
        costScale: 2.2,
        maxLevel: 1,
        unlockFlag: 'unlock-bulk-filing',
        unlockMessage: 'Bulk Drop unlocked. Big batches can move in one hit.',
    },
    overtimeProgram: {
        id: 'overtimeProgram',
        title: 'Night Shift Operations',
        tier: 'department',
        description: 'Breakthrough: double operations',
        baseCost: 160,
        costScale: 2.35,
        maxLevel: 1,
        unlockFlag: 'unlock-overtime-program',
        unlockMessage: 'Night Shift Operations unlocked. The whole line just doubled its pace.',
    },
    federalSubsidy: {
        id: 'federalSubsidy',
        title: 'Major Deal',
        tier: 'agency',
        description: 'Double all cash',
        baseCost: 280,
        costScale: 2.5,
        maxLevel: 1,
        unlockFlag: 'unlock-federal-subsidy',
        unlockMessage: 'Major Deal unlocked. One big score just changed the whole operation.',
    },
};

export const STATUS_MESSAGES = {
    arrival: [
        'Another order came in through a quiet channel.',
        'A contact just dropped fresh work on the table.',
        'Demand is picking up in the shadows.',
        'One more client wants the job handled quietly.',
    ],
    automation: [
        'A runner cleared a job without asking questions.',
        'An operator moved product before anyone noticed.',
        'The night crew kept the line moving.',
        'A clean handoff pushed another order through.',
    ],
    growth: [
        'The chain of command just got deeper.',
        'Another crew leader came on board.',
        'Storage and routes are starting to look serious.',
        'The operation is getting harder to trace.',
    ],
    unlocked: [
        'Word is spreading. The network is growing.',
        'The operation just stepped into a bigger league.',
        'Your name is starting to carry weight.',
    ],
};
