export const SAVE_KEY = 'bureaucracy-tycoon-save-v1';

export const ECONOMY = {
    startingMoney: 0,
    startingPendingForms: 3,
    startingCapacity: 14,
    startingMoneyPerForm: 1,
    startingMoneyMultiplier: 1,
    startingArrivalRate: 1.2,
    startingAutoProcessRate: 0,
    manualProcessAmount: 2,
    approvalLayerBonus: 0.22,
    overflowWarningThreshold: 0.9,
    surgeQueueThreshold: 0.75,
    surgeIntervalSeconds: 6,
    surgeProcessAmount: 3,
    passiveSaveSeconds: 5,
    tickRateMs: 100,
    logLimit: 4,
    contractBudgetRewardMultiplier: 1.6,
};

export const UPGRADE_DEFINITIONS = {
    betterInk: {
        id: 'betterInk',
        title: 'Better Ink',
        tier: 'office',
        description: '+1 money per processed form',
        baseCost: 8,
        costScale: 1.42,
    },
    largerInbox: {
        id: 'largerInbox',
        title: 'Larger Inbox',
        tier: 'office',
        description: '+8 queue capacity',
        baseCost: 20,
        costScale: 1.52,
    },
    juniorClerk: {
        id: 'juniorClerk',
        title: 'Junior Clerk',
        tier: 'office',
        description: '+1 auto-process per second',
        baseCost: 12,
        costScale: 1.5,
    },
    marketingCampaign: {
        id: 'marketingCampaign',
        title: 'Marketing Campaign',
        tier: 'office',
        description: '+0.75 forms per second',
        baseCost: 16,
        costScale: 1.5,
    },
    complianceDesk: {
        id: 'complianceDesk',
        title: 'Compliance Desk',
        tier: 'department',
        description: '+25% money multiplier',
        baseCost: 52,
        costScale: 1.72,
    },
    approvalLayer: {
        id: 'approvalLayer',
        title: 'Approval Layer',
        tier: 'department',
        description: 'Increase bureaucracy level and boost all scaling',
        baseCost: 90,
        costScale: 1.95,
    },
    expressWindow: {
        id: 'expressWindow',
        title: 'Express Window',
        tier: 'office',
        description: '+1 form per manual stamp',
        baseCost: 20,
        costScale: 1.62,
    },
    seniorClerk: {
        id: 'seniorClerk',
        title: 'Senior Clerk',
        tier: 'department',
        description: '+2 auto-process per second',
        baseCost: 70,
        costScale: 1.82,
        unlockFlag: 'unlock-senior-clerk',
        unlockMessage: 'Senior Clerk unlocked. The department finally hired someone with a keyring.',
    },
    efficiencyOffice: {
        id: 'efficiencyOffice',
        title: 'Efficiency Office',
        tier: 'agency',
        description: '+15% processing efficiency',
        baseCost: 85,
        costScale: 1.88,
    },
    doubleStamp: {
        id: 'doubleStamp',
        title: 'Double Stamp',
        tier: 'department',
        description: '+1 extra form per manual stamp',
        baseCost: 90,
        costScale: 2.2,
        maxLevel: 1,
        unlockFlag: 'unlock-double-stamp',
        unlockMessage: 'Double Stamp unlocked. Management now permits paired paperwork.',
    },
    surgeProtocol: {
        id: 'surgeProtocol',
        title: 'Surge Protocol',
        tier: 'agency',
        description: 'Every 6 seconds, burst-process 3 forms when the inbox is crowded',
        baseCost: 160,
        costScale: 2.35,
        maxLevel: 1,
        unlockFlag: 'unlock-surge-protocol',
        unlockMessage: 'Surge Protocol unlocked. Emergency throughput remains deeply procedural.',
    },
    bulkFiling: {
        id: 'bulkFiling',
        title: 'Bulk Filing',
        tier: 'department',
        description: '+3 forms per manual stamp',
        baseCost: 110,
        costScale: 2.2,
        maxLevel: 1,
        unlockFlag: 'unlock-bulk-filing',
        unlockMessage: 'Bulk Filing unlocked. Entire stacks may now be stamped at once.',
    },
    overtimeProgram: {
        id: 'overtimeProgram',
        title: 'Overtime Program',
        tier: 'department',
        description: 'Breakthrough: double auto-processing',
        baseCost: 160,
        costScale: 2.35,
        maxLevel: 1,
        unlockFlag: 'unlock-overtime-program',
        unlockMessage: 'Overtime Program unlocked. Automation capacity just doubled.',
    },
    federalSubsidy: {
        id: 'federalSubsidy',
        title: 'Federal Subsidy',
        tier: 'agency',
        description: 'Double all income',
        baseCost: 280,
        costScale: 2.5,
        maxLevel: 1,
        unlockFlag: 'unlock-federal-subsidy',
        unlockMessage: 'Federal Subsidy unlocked. Treasury support has arrived in ceremonial quantities.',
    },
};

export const STATUS_MESSAGES = {
    arrival: [
        'Form returned for missing signature.',
        'Citizen redirected to Auxiliary Review.',
        'Inbox tray bends under procedural pressure.',
        'Courier adds another folder to the national backlog.',
    ],
    automation: [
        'Clerk promoted to Senior Delay Associate.',
        'A memo confirms the memo about processing.',
        'Auto-stamping proceeds after committee hesitation.',
        'Another desk has been authorized to shuffle paper faster.',
    ],
    growth: [
        'New approval layer added.',
        'A subcommittee has been formed to monitor throughput.',
        'Efficiency report misplaced in triplicate.',
        'Department renamed for strategic confusion.',
    ],
    unlocked: [
        'Citizens now take numbered tickets.',
        'Break room rumors predict further expansion.',
        'Someone found the ceremonial stamp pad.',
    ],
};
